### ISSUE TITLE
mash_playbook_reverse_proxy_type: none isn't  taken into account

### ISSUE THREAD

**Issue by JokerGermany** [mother-of-all-self-hosting/ansible-role-paperless#3]
```
TASK [galaxy/paperless : Ensure paperless traefik labels are installed] *************************************************************************************************
failed: [example.com] (item={'src': '/media/HDD/Downloads/mash-playbook/roles/galaxy/paperless/templates/labels.j2', 'dest': '/media/wichtig/server/mash/paperless/labels'}) => changed=false 
  ansible_loop_var: item
  item:
    dest: /media/wichtig/server/mash/paperless/labels
    src: /media/HDD/Downloads/mash-playbook/roles/galaxy/paperless/templates/labels.j2
  msg: 'AnsibleUndefinedVariable: ''middlewares'' is undefined'
```

A workaround was deleting in the install.yml this:
```
- name: Ensure paperless traefik labels are installed
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ paperless_uid }}"
    group: "{{ paperless_gid }}"
    mode: 0640
  with_items:
    - {src: "{{ role_path }}/templates/labels.j2", dest: "{{ paperless_base_path }}/labels"}
```
and comment out in the paperless.service.j2 this:
`--label-file={{ paperless_base_path }}/labels \`
